In [1]:
import pandas as pd

In [48]:
df = pd.read_csv("df45.csv", encoding="utf-8", sep=";")
df.head(20)

,Kodutöö,Õpilane,Ülesanne,Tekst
0,K01,S001,kodu1.py,from turtle import *\n\nforward(250)\nright(13...
1,K01,S002,kodu1.py,from turtle import *\nimport math\n\nfd(40)\nr...
2,K01,S003,kodu1.py,"from turtle import *\n\nfillcolor(""brown"")\n\n..."
3,K01,S004,kodu1.py,import turtle\np=turtle.Turtle(visible=False)\...
4,K01,S005,kodu1.py,import turtle\n# set turtle colour to black\nt...
5,K01,S006,kodu1.py,from turtle import*\n\nforward(240)\nleft(41)\...
6,K01,S007,kodu1.py,from turtle import *\n\npensize(3)\nright(135)...
7,K01,S008,kodu1.py,from turtle import *\n\n#mootorpaat\n\nforward...
8,K01,S009,kodu1.py,from turtle import*\n\nforward(120)\nright(120...
9,K01,S010,kodu1.py,from turtle import *\nforward(200)\nleft(45)\n...
10,K01,S011,kodu1.py,from turtle import *\nforward(100)\nleft(60)\n...
11,K01,S012,kodu1.py,"from turtle import *\nspeed(0)\nfillcolor(""bro..."
12,K01,S013,kodu1.py,from turtle import *\n\nforward(250)\nleft(30)...
13,K01,S014,kodu1.py,from turtle import *\n\nforward(150)\nleft(35)...
14,K01,S015,kodu1.py,# Modules\nimport turtle\nfrom math import sqr...
15,K01,S016,kodu1.py,"#a = float(input(""Sisesta oma arv: ""))\n#print..."
16,K01,S017,kodu1.py,from turtle import *\n\nforward(125)\nleft(45)...
17,K01,S018,kodu1.py,from turtle import *\n\n#kere\nforward(150)\n...
18,K01,S019,kodu1.py,from turtle import *\n\nup()\nright(90)\nforwa...
19,K01,S020,kodu1.py,"from turtle import *\n\ncolor(""blue"", """")\nfor..."

In [49]:
# how many lines were dedicated to a comment starting with a "#"
df["commented_lines"] = df["Tekst"].str.count("#[^#]")
# how many lines were left blank
df["blank_lines"] = df["Tekst"].str.count("\n\n")
# how many lines had code in them
df["code_lines"] = df["Tekst"].str.count("\n") - df["commented_lines"] - df["blank_lines"] + 1
# how many symbols were there on average per line
df["characters_per_line"] = df["Tekst"].str.len() / (df["commented_lines"] + df["blank_lines"] + df["code_lines"])
# how many times was a class defined
df["class_definitions"] = df["Tekst"].str.count("class .+ *:")
# how many times was a function defined
df["function_definitions"] = df["Tekst"].str.count("def .+\(.*\) *:")
# how many times was a function called (note that this will also count how many times objects were created because the syntax is the same)
df["function_calls"] = df["Tekst"].str.count(".+\(.*\)[^:]")
# how many times was a module from a library imported
df["imported_modules"] = df["Tekst"].str.count("from .+ import")
# how many times was an entire library imported
df["imported_libararies"] = df["Tekst"].str.count("import") - df["imported_modules"]
# how many times was an object's property accessed (with the syntax of "object.property")
df["properties_accessed"] = df["Tekst"].str.count("[^ ]\.[^ ]")
# how many times was a variable assigned a value
df["variable_assignments"] = df["Tekst"].str.count("[^=+-<>]=[^=]")
# how many times were values of variables compared with "=="
df["variable_comparisons"] = df["Tekst"].str.count("==")
# how many times were values of variables compared with "!="
df["variable_not_comparisons"] = df["Tekst"].str.count("!=")
# how many times was a value of a variable incremented with "+="
df["variable_increments"] = df["Tekst"].str.count("\+=")
# how many times was a value of a variable decremented with "-="
df["variable_decrements"] = df["Tekst"].str.count("-=")
# how many times was a piece of code written with camel-case syntax (format is "camelCase")
df["camel_case_instances"] = df["Tekst"].str.count("[a-zäöüõšž][A-ZÄÖÜÕŠŽ]")
# how many times was a piece of code written with snake-case syntax (format is "snake_case")
df["snake_case_instances"] = df["Tekst"].str.count("[a-zäöüõšž]_[a-zäöüõšž]|[A-ZÄÖÜÕŠŽ]_[A-ZÄÖÜÕŠŽ]")
# how many times was an array (or rather a list) declared
df["array_declarations"] = df["Tekst"].str.count("[ =]\[.*\]")
# how many times was a value of an array accessed by index
df["accesses_by_index"] = df["Tekst"].str.count("\[.*\]") - df["array_declarations"]
# how many times was a set declared
df["set_declarations"] = df["Tekst"].str.count("set\(.*\)")
# how many times was a string literal used (strings literals being text between "" or '')
df["string_literals"] = df["Tekst"].str.count("\".*\"|'.*'")
# how many times was an if statement used
df["if_statements"] = df["Tekst"].str.count("[\n| ]if .+:")
# how many times was an elif statement used
df["elif_statements"] = df["Tekst"].str.count("[\n| ]elif .+:")
# how many times was an else statement used
df["else_statements"] = df["Tekst"].str.count("[\n| ]else *:")
# how many times was a try statement used
df["try_statements"] = df["Tekst"].str.count("[\n| ]try *:")
# how many times was an except statement used
df["except_statements"] = df["Tekst"].str.count("[\n| ]except *:")
# how many times was a with statement used
df["with_statements"] = df["Tekst"].str.count("[\n| ]with .+:")
# how many times was a not statement used
df["not_statements"] = df["Tekst"].str.count(" not ")
# how many times was a while loop used
df["while_loops"] = df["Tekst"].str.count("[\n| ]while .+:")
# how many times was a for loop used
df["for_loops"] = df["Tekst"].str.count("[\n| ]for .+:")
df.head(20)

,Kodutöö,Õpilane,Ülesanne,Tekst,commented_lines,blank_lines,code_lines,characters_per_line,class_definitions,function_definitions,...,string_literals,if_statements,elif_statements,else_statements,try_statements,except_statements,with_statements,not_statements,while_loops,for_loops
0,K01,S001,kodu1.py,from turtle import *\n\nforward(250)\nright(13...,0.0,4.0,31.0,10.228571,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,K01,S002,kodu1.py,from turtle import *\nimport math\n\nfd(40)\nr...,0.0,6.0,52.0,10.482759,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,K01,S003,kodu1.py,"from turtle import *\n\nfillcolor(""brown"")\n\n...",0.0,3.0,34.0,10.513514,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,K01,S004,kodu1.py,import turtle\np=turtle.Turtle(visible=False)\...,0.0,0.0,30.0,15.300000,0.0,0.0,...,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,K01,S005,kodu1.py,import turtle\n# set turtle colour to black\nt...,6.0,0.0,43.0,19.816327,0.0,1.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,K01,S006,kodu1.py,from turtle import*\n\nforward(240)\nleft(41)\...,0.0,1.0,30.0,10.903226,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,K01,S007,kodu1.py,from turtle import *\n\npensize(3)\nright(135)...,0.0,3.0,23.0,10.846154,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,K01,S008,kodu1.py,from turtle import *\n\n#mootorpaat\n\nforward...,1.0,2.0,31.0,10.647059,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,K01,S009,kodu1.py,from turtle import*\n\nforward(120)\nright(120...,0.0,5.0,23.0,9.750000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,K01,S010,kodu1.py,from turtle import *\nforward(200)\nleft(45)\n...,0.0,2.0,44.0,10.869565,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,K01,S011,kodu1.py,from turtle import *\nforward(100)\nleft(60)\n...,0.0,0.0,25.0,11.200000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,K01,S012,kodu1.py,"from turtle import *\nspeed(0)\nfillcolor(""bro...",0.0,3.0,87.0,9.944444,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,K01,S013,kodu1.py,from turtle import *\n\nforward(250)\nleft(30)...,0.0,1.0,29.0,11.033333,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,K01,S014,kodu1.py,from turtle import *\n\nforward(150)\nleft(35)...,0.0,7.0,80.0,9.137931,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,K01,S015,kodu1.py,# Modules\nimport turtle\nfrom math import sqr...,9.0,3.0,57.0,17.840580,1.0,5.0,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,K01,S016,kodu1.py,"#a = float(input(""Sisesta oma arv: ""))\n#print...",13.0,3.0,35.0,14.509804,0.0,0.0,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,K01,S017,kodu1.py,from turtle import *\n\nforward(125)\nleft(45)...,0.0,3.0,24.0,9.555556,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,K01,S018,kodu1.py,from turtle import *\n\n#kere\nforward(150)\n...,5.0,6.0,35.0,10.043478,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,K01,S019,kodu1.py,from turtle import *\n\nup()\nright(90)\nforwa...,0.0,6.0,38.0,10.022727,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,K01,S020,kodu1.py,"from turtle import *\n\ncolor(""blue"", """")\nfor...",10.0,7.0,21.0,9.973684,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
df.to_csv("df_with_features.csv", encoding="utf-8", index=True, sep=";")